sudo: required

services:
  - docker

script:
  # Build images
  - docker build -t jmeisele/micromodel_airflow ./src/airflow
  - docker build -t jmeisele/micromodel_chronograph ./src/chronograf
  - docker build -t jmeisele/micromodel_influxdb ./src/influxdb
  - docker build -t jmeisele/micromodel_grafana ./src/grafana
  - docker build -t jmeisele/micromodel_mlflow ./src/mlflow
  - docker build -t jmeisele/micromodel_nginx ./src/nginx
  - docker build -t jmeisele/micromodel_python-model-service-1 ./src/python-model-service-1
  - docker build -t jmeisele/micromodel_python-model-service-2 ./src/python-model-service-2
  - docker build -t jmeisele/micromodel_rabbitmq-server ./src/rabbitmq-server
  - docker build -t jmeisele/micromodel_telegraf ./src/telegraf

after_success:
  # Login to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to DockerHub
  - docker push jmeisele/micromodel_airflow
  - docker push jmeisele/micromodel_chronograph
  - docker push jmeisele/micromodel_influxdb
  - docker push jmeisele/micromodel_grafana
  - docker push jmeisele/micromodel_mlflow
  - docker push jmeisele/micromodel_nginx
  - docker push jmeisele/micromodel_python-model-service-1
  - docker push jmeisele/micromodel_python-model-service-2
  - docker push jmeisele/micromodel_rabbitmq-server
  - docker push jmeisele/micromodel_telegraf
    
# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "docker-flask"
#     env: "DockerFlask-env"
#     bucket_name: "elasticbeanstalk-us-east-2-726690209754"
#     bucket_path: "docker-flask"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY