
chronograf:
container_name: chronograf
image: chronograf:1.8.4-alpine
restart: unless-stopped
user: "0"
ports:
    - 8888:8888
env_file:
    - ./src/chronograf/chronograf.env
volumes:
    - ./volumes/chronograf/data:/var/lib/chronograf
    - ./volumes/chronograf/log:/var/log/chronograf